import '../models/sourate.dart';

class _SourateName {
  final int id;
  final String nameAr;
  final String nameFr;
  const _SourateName(this.id, this.nameAr, this.nameFr);
}

/// 113 sourates (Al-Fatiha exclue — récitée à chaque rakaa automatiquement).
/// Id/noms sont riwaya-indépendants ; les comptes de versets/mots sont
/// injectés via [buildSourates] depuis HafsService/WarshService, car ils
/// diffèrent entre Hafs (6236 versets au total) et Warsh (6214).
const List<_SourateName> _sourateNames = [
  _SourateName(2, 'البقرة', 'Al-Baqara'),
  _SourateName(3, 'آل عمران', 'Al-Imran'),
  _SourateName(4, 'النساء', 'An-Nisa'),
  _SourateName(5, 'المائدة', 'Al-Maida'),
  _SourateName(6, 'الأنعام', 'Al-Anam'),
  _SourateName(7, 'الأعراف', 'Al-Araf'),
  _SourateName(8, 'الأنفال', 'Al-Anfal'),
  _SourateName(9, 'التوبة', 'At-Tawba'),
  _SourateName(10, 'يونس', 'Yunus'),
  _SourateName(11, 'هود', 'Hud'),
  _SourateName(12, 'يوسف', 'Yusuf'),
  _SourateName(13, 'الرعد', 'Ar-Rad'),
  _SourateName(14, 'إبراهيم', 'Ibrahim'),
  _SourateName(15, 'الحجر', 'Al-Hijr'),
  _SourateName(16, 'النحل', 'An-Nahl'),
  _SourateName(17, 'الإسراء', 'Al-Isra'),
  _SourateName(18, 'الكهف', 'Al-Kahf'),
  _SourateName(19, 'مريم', 'Maryam'),
  _SourateName(20, 'طه', 'Ta-Ha'),
  _SourateName(21, 'الأنبياء', 'Al-Anbiya'),
  _SourateName(22, 'الحج', 'Al-Hajj'),
  _SourateName(23, 'المؤمنون', 'Al-Muminun'),
  _SourateName(24, 'النور', 'An-Nur'),
  _SourateName(25, 'الفرقان', 'Al-Furqan'),
  _SourateName(26, 'الشعراء', 'Ash-Shuara'),
  _SourateName(27, 'النمل', 'An-Naml'),
  _SourateName(28, 'القصص', 'Al-Qasas'),
  _SourateName(29, 'العنكبوت', 'Al-Ankabut'),
  _SourateName(30, 'الروم', 'Ar-Rum'),
  _SourateName(31, 'لقمان', 'Luqman'),
  _SourateName(32, 'السجدة', 'As-Sajda'),
  _SourateName(33, 'الأحزاب', 'Al-Ahzab'),
  _SourateName(34, 'سبأ', 'Saba'),
  _SourateName(35, 'فاطر', 'Fatir'),
  _SourateName(36, 'يس', 'Ya-Sin'),
  _SourateName(37, 'الصافات', 'As-Saffat'),
  _SourateName(38, 'ص', 'Sad'),
  _SourateName(39, 'الزمر', 'Az-Zumar'),
  _SourateName(40, 'غافر', 'Ghafir'),
  _SourateName(41, 'فصلت', 'Fussilat'),
  _SourateName(42, 'الشورى', 'Ash-Shura'),
  _SourateName(43, 'الزخرف', 'Az-Zukhruf'),
  _SourateName(44, 'الدخان', 'Ad-Dukhan'),
  _SourateName(45, 'الجاثية', 'Al-Jathiya'),
  _SourateName(46, 'الأحقاف', 'Al-Ahqaf'),
  _SourateName(47, 'محمد', 'Muhammad'),
  _SourateName(48, 'الفتح', 'Al-Fath'),
  _SourateName(49, 'الحجرات', 'Al-Hujurat'),
  _SourateName(50, 'ق', 'Qaf'),
  _SourateName(51, 'الذاريات', 'Adh-Dhariyat'),
  _SourateName(52, 'الطور', 'At-Tur'),
  _SourateName(53, 'النجم', 'An-Najm'),
  _SourateName(54, 'القمر', 'Al-Qamar'),
  _SourateName(55, 'الرحمن', 'Ar-Rahman'),
  _SourateName(56, 'الواقعة', 'Al-Waqia'),
  _SourateName(57, 'الحديد', 'Al-Hadid'),
  _SourateName(58, 'المجادلة', 'Al-Mujadila'),
  _SourateName(59, 'الحشر', 'Al-Hashr'),
  _SourateName(60, 'الممتحنة', 'Al-Mumtahana'),
  _SourateName(61, 'الصف', 'As-Saf'),
  _SourateName(62, 'الجمعة', 'Al-Jumuah'),
  _SourateName(63, 'المنافقون', 'Al-Munafiqun'),
  _SourateName(64, 'التغابن', 'At-Taghabun'),
  _SourateName(65, 'الطلاق', 'At-Talaq'),
  _SourateName(66, 'التحريم', 'At-Tahrim'),
  _SourateName(67, 'الملك', 'Al-Mulk'),
  _SourateName(68, 'القلم', 'Al-Qalam'),
  _SourateName(69, 'الحاقة', 'Al-Haqqa'),
  _SourateName(70, 'المعارج', 'Al-Maarij'),
  _SourateName(71, 'نوح', 'Nuh'),
  _SourateName(72, 'الجن', 'Al-Jinn'),
  _SourateName(73, 'المزمل', 'Al-Muzzammil'),
  _SourateName(74, 'المدثر', 'Al-Muddaththir'),
  _SourateName(75, 'القيامة', 'Al-Qiyama'),
  _SourateName(76, 'الإنسان', 'Al-Insan'),
  _SourateName(77, 'المرسلات', 'Al-Mursalat'),
  _SourateName(78, 'النبأ', 'An-Naba'),
  _SourateName(79, 'النازعات', 'An-Naziat'),
  _SourateName(80, 'عبس', 'Abasa'),
  _SourateName(81, 'التكوير', 'At-Takwir'),
  _SourateName(82, 'الانفطار', 'Al-Infitar'),
  _SourateName(83, 'المطففين', 'Al-Mutaffifin'),
  _SourateName(84, 'الانشقاق', 'Al-Inshiqaq'),
  _SourateName(85, 'البروج', 'Al-Buruj'),
  _SourateName(86, 'الطارق', 'At-Tariq'),
  _SourateName(87, 'الأعلى', "Al-A'la"),
  _SourateName(88, 'الغاشية', 'Al-Ghashiya'),
  _SourateName(89, 'الفجر', 'Al-Fajr'),
  _SourateName(90, 'البلد', 'Al-Balad'),
  _SourateName(91, 'الشمس', 'Ash-Shams'),
  _SourateName(92, 'الليل', 'Al-Layl'),
  _SourateName(93, 'الضحى', 'Ad-Duha'),
  _SourateName(94, 'الشرح', 'Ash-Sharh'),
  _SourateName(95, 'التين', 'At-Tin'),
  _SourateName(96, 'العلق', "Al-Alaq"),
  _SourateName(97, 'القدر', 'Al-Qadr'),
  _SourateName(98, 'البينة', 'Al-Bayyina'),
  _SourateName(99, 'الزلزلة', 'Az-Zalzala'),
  _SourateName(100, 'العاديات', 'Al-Adiyat'),
  _SourateName(101, 'القارعة', "Al-Qari'a"),
  _SourateName(102, 'التكاثر', 'At-Takathur'),
  _SourateName(103, 'العصر', "Al-Asr"),
  _SourateName(104, 'الهمزة', 'Al-Humaza'),
  _SourateName(105, 'الفيل', 'Al-Fil'),
  _SourateName(106, 'قريش', 'Quraysh'),
  _SourateName(107, 'الماعون', "Al-Ma'un"),
  _SourateName(108, 'الكوثر', 'Al-Kawthar'),
  _SourateName(109, 'الكافرون', 'Al-Kafirun'),
  _SourateName(110, 'النصر', 'An-Nasr'),
  _SourateName(111, 'المسد', 'Al-Masad'),
  _SourateName(112, 'الإخلاص', 'Al-Ikhlas'),
  _SourateName(113, 'الفلق', 'Al-Falaq'),
  _SourateName(114, 'الناس', 'An-Nas'),
];

/// Construit la liste des 113 sourates pour une riwaya donnée, à partir des
/// comptes de versets/mots chargés depuis HafsService/WarshService. Fonction
/// pure — aucun I/O ici, les données viennent déjà chargées de la couche
/// services.
List<Sourate> buildSourates({
  required Map<int, int> verseCounts,
  required Map<int, int> wordCounts,
}) =>
    _sourateNames
        .map((n) => Sourate(
              id: n.id,
              nameAr: n.nameAr,
              nameFr: n.nameFr,
              verses: verseCounts[n.id]!,
              words: wordCounts[n.id]!,
            ))
        .toList();
