import '../models/sourate.dart';

/// 113 sourates (Al-Fatiha exclue — récitée à chaque rakaa automatiquement)
/// Le champ `words` est le nombre de mots arabes de chaque sourate.
const List<Sourate> allSourates = [
  Sourate(id: 2,   nameAr: 'البقرة',        nameFr: 'Al-Baqara',     verses: 286, words: 6144),
  Sourate(id: 3,   nameAr: 'آل عمران',      nameFr: 'Al-Imran',      verses: 200, words: 3503),
  Sourate(id: 4,   nameAr: 'النساء',        nameFr: 'An-Nisa',       verses: 176, words: 3745),
  Sourate(id: 5,   nameAr: 'المائدة',       nameFr: 'Al-Maida',      verses: 120, words: 2837),
  Sourate(id: 6,   nameAr: 'الأنعام',       nameFr: 'Al-Anam',       verses: 165, words: 3055),
  Sourate(id: 7,   nameAr: 'الأعراف',       nameFr: 'Al-Araf',       verses: 206, words: 3344),
  Sourate(id: 8,   nameAr: 'الأنفال',       nameFr: 'Al-Anfal',      verses: 75,  words: 1242),
  Sourate(id: 9,   nameAr: 'التوبة',        nameFr: 'At-Tawba',      verses: 129, words: 2506),
  Sourate(id: 10,  nameAr: 'يونس',          nameFr: 'Yunus',         verses: 109, words: 1839),
  Sourate(id: 11,  nameAr: 'هود',           nameFr: 'Hud',           verses: 123, words: 1946),
  Sourate(id: 12,  nameAr: 'يوسف',          nameFr: 'Yusuf',         verses: 111, words: 1795),
  Sourate(id: 13,  nameAr: 'الرعد',         nameFr: 'Ar-Rad',        verses: 43,  words: 854),
  Sourate(id: 14,  nameAr: 'إبراهيم',       nameFr: 'Ibrahim',       verses: 52,  words: 831),
  Sourate(id: 15,  nameAr: 'الحجر',         nameFr: 'Al-Hijr',       verses: 99,  words: 654),
  Sourate(id: 16,  nameAr: 'النحل',         nameFr: 'An-Nahl',       verses: 128, words: 1841),
  Sourate(id: 17,  nameAr: 'الإسراء',       nameFr: 'Al-Isra',       verses: 111, words: 1555),
  Sourate(id: 18,  nameAr: 'الكهف',         nameFr: 'Al-Kahf',       verses: 110, words: 1584),
  Sourate(id: 19,  nameAr: 'مريم',          nameFr: 'Maryam',        verses: 98,  words: 972),
  Sourate(id: 20,  nameAr: 'طه',            nameFr: 'Ta-Ha',         verses: 135, words: 1353),
  Sourate(id: 21,  nameAr: 'الأنبياء',      nameFr: 'Al-Anbiya',     verses: 112, words: 1183),
  Sourate(id: 22,  nameAr: 'الحج',          nameFr: 'Al-Hajj',       verses: 78,  words: 1282),
  Sourate(id: 23,  nameAr: 'المؤمنون',      nameFr: 'Al-Muminun',    verses: 118, words: 1054),
  Sourate(id: 24,  nameAr: 'النور',         nameFr: 'An-Nur',        verses: 64,  words: 1316),
  Sourate(id: 25,  nameAr: 'الفرقان',       nameFr: 'Al-Furqan',     verses: 77,  words: 896),
  Sourate(id: 26,  nameAr: 'الشعراء',       nameFr: 'Ash-Shuara',    verses: 227, words: 1322),
  Sourate(id: 27,  nameAr: 'النمل',         nameFr: 'An-Naml',       verses: 93,  words: 1163),
  Sourate(id: 28,  nameAr: 'القصص',         nameFr: 'Al-Qasas',      verses: 88,  words: 1441),
  Sourate(id: 29,  nameAr: 'العنكبوت',      nameFr: 'Al-Ankabut',    verses: 69,  words: 978),
  Sourate(id: 30,  nameAr: 'الروم',         nameFr: 'Ar-Rum',        verses: 60,  words: 817),
  Sourate(id: 31,  nameAr: 'لقمان',         nameFr: 'Luqman',        verses: 34,  words: 548),
  Sourate(id: 32,  nameAr: 'السجدة',        nameFr: 'As-Sajda',      verses: 30,  words: 374),
  Sourate(id: 33,  nameAr: 'الأحزاب',       nameFr: 'Al-Ahzab',      verses: 73,  words: 1303),
  Sourate(id: 34,  nameAr: 'سبأ',           nameFr: 'Saba',          verses: 54,  words: 883),
  Sourate(id: 35,  nameAr: 'فاطر',          nameFr: 'Fatir',         verses: 45,  words: 779),
  Sourate(id: 36,  nameAr: 'يس',            nameFr: 'Ya-Sin',        verses: 83,  words: 729),
  Sourate(id: 37,  nameAr: 'الصافات',       nameFr: 'As-Saffat',     verses: 182, words: 865),
  Sourate(id: 38,  nameAr: 'ص',             nameFr: 'Sad',           verses: 88,  words: 735),
  Sourate(id: 39,  nameAr: 'الزمر',         nameFr: 'Az-Zumar',      verses: 75,  words: 1178),
  Sourate(id: 40,  nameAr: 'غافر',          nameFr: 'Ghafir',        verses: 85,  words: 1228),
  Sourate(id: 41,  nameAr: 'فصلت',          nameFr: 'Fussilat',      verses: 54,  words: 795),
  Sourate(id: 42,  nameAr: 'الشورى',        nameFr: 'Ash-Shura',     verses: 53,  words: 860),
  Sourate(id: 43,  nameAr: 'الزخرف',        nameFr: 'Az-Zukhruf',    verses: 89,  words: 836),
  Sourate(id: 44,  nameAr: 'الدخان',        nameFr: 'Ad-Dukhan',     verses: 59,  words: 346),
  Sourate(id: 45,  nameAr: 'الجاثية',       nameFr: 'Al-Jathiya',    verses: 37,  words: 488),
  Sourate(id: 46,  nameAr: 'الأحقاف',       nameFr: 'Al-Ahqaf',      verses: 35,  words: 648),
  Sourate(id: 47,  nameAr: 'محمد',          nameFr: 'Muhammad',      verses: 38,  words: 542),
  Sourate(id: 48,  nameAr: 'الفتح',         nameFr: 'Al-Fath',       verses: 29,  words: 560),
  Sourate(id: 49,  nameAr: 'الحجرات',       nameFr: 'Al-Hujurat',    verses: 18,  words: 353),
  Sourate(id: 50,  nameAr: 'ق',             nameFr: 'Qaf',           verses: 45,  words: 373),
  Sourate(id: 51,  nameAr: 'الذاريات',      nameFr: 'Adh-Dhariyat',  verses: 60,  words: 360),
  Sourate(id: 52,  nameAr: 'الطور',         nameFr: 'At-Tur',        verses: 49,  words: 312),
  Sourate(id: 53,  nameAr: 'النجم',         nameFr: 'An-Najm',       verses: 62,  words: 360),
  Sourate(id: 54,  nameAr: 'القمر',         nameFr: 'Al-Qamar',      verses: 55,  words: 342),
  Sourate(id: 55,  nameAr: 'الرحمن',        nameFr: 'Ar-Rahman',     verses: 78,  words: 352),
  Sourate(id: 56,  nameAr: 'الواقعة',       nameFr: 'Al-Waqia',      verses: 96,  words: 379),
  Sourate(id: 57,  nameAr: 'الحديد',        nameFr: 'Al-Hadid',      verses: 29,  words: 576),
  Sourate(id: 58,  nameAr: 'المجادلة',      nameFr: 'Al-Mujadila',   verses: 22,  words: 475),
  Sourate(id: 59,  nameAr: 'الحشر',         nameFr: 'Al-Hashr',      verses: 24,  words: 445),
  Sourate(id: 60,  nameAr: 'الممتحنة',      nameFr: 'Al-Mumtahana',  verses: 13,  words: 358),
  Sourate(id: 61,  nameAr: 'الصف',          nameFr: 'As-Saf',        verses: 14,  words: 221),
  Sourate(id: 62,  nameAr: 'الجمعة',        nameFr: 'Al-Jumuah',     verses: 11,  words: 172),
  Sourate(id: 63,  nameAr: 'المنافقون',     nameFr: 'Al-Munafiqun',  verses: 11,  words: 181),
  Sourate(id: 64,  nameAr: 'التغابن',       nameFr: 'At-Taghabun',   verses: 18,  words: 241),
  Sourate(id: 65,  nameAr: 'الطلاق',        nameFr: 'At-Talaq',      verses: 12,  words: 253),
  Sourate(id: 66,  nameAr: 'التحريم',       nameFr: 'At-Tahrim',     verses: 12,  words: 254),
  Sourate(id: 67,  nameAr: 'الملك',         nameFr: 'Al-Mulk',       verses: 30,  words: 333),
  Sourate(id: 68,  nameAr: 'القلم',         nameFr: 'Al-Qalam',      verses: 52,  words: 301),
  Sourate(id: 69,  nameAr: 'الحاقة',        nameFr: 'Al-Haqqa',      verses: 52,  words: 260),
  Sourate(id: 70,  nameAr: 'المعارج',       nameFr: 'Al-Maarij',     verses: 44,  words: 217),
  Sourate(id: 71,  nameAr: 'نوح',           nameFr: 'Nuh',           verses: 28,  words: 227),
  Sourate(id: 72,  nameAr: 'الجن',          nameFr: 'Al-Jinn',       verses: 28,  words: 285),
  Sourate(id: 73,  nameAr: 'المزمل',        nameFr: 'Al-Muzzammil',  verses: 20,  words: 199),
  Sourate(id: 74,  nameAr: 'المدثر',        nameFr: 'Al-Muddaththir',verses: 56,  words: 256),
  Sourate(id: 75,  nameAr: 'القيامة',       nameFr: 'Al-Qiyama',     verses: 40,  words: 199),
  Sourate(id: 76,  nameAr: 'الإنسان',       nameFr: 'Al-Insan',      verses: 31,  words: 243),
  Sourate(id: 77,  nameAr: 'المرسلات',      nameFr: 'Al-Mursalat',   verses: 50,  words: 181),
  Sourate(id: 78,  nameAr: 'النبأ',         nameFr: 'An-Naba',       verses: 40,  words: 174),
  Sourate(id: 79,  nameAr: 'النازعات',      nameFr: 'An-Naziat',     verses: 46,  words: 179),
  Sourate(id: 80,  nameAr: 'عبس',           nameFr: 'Abasa',         verses: 42,  words: 133),
  Sourate(id: 81,  nameAr: 'التكوير',       nameFr: 'At-Takwir',     verses: 29,  words: 104),
  Sourate(id: 82,  nameAr: 'الانفطار',      nameFr: 'Al-Infitar',    verses: 19,  words: 81),
  Sourate(id: 83,  nameAr: 'المطففين',      nameFr: 'Al-Mutaffifin', verses: 36,  words: 170),
  Sourate(id: 84,  nameAr: 'الانشقاق',      nameFr: 'Al-Inshiqaq',   verses: 25,  words: 107),
  Sourate(id: 85,  nameAr: 'البروج',        nameFr: 'Al-Buruj',      verses: 22,  words: 109),
  Sourate(id: 86,  nameAr: 'الطارق',        nameFr: 'At-Tariq',      verses: 17,  words: 61),
  Sourate(id: 87,  nameAr: 'الأعلى',        nameFr: "Al-A'la",       verses: 19,  words: 72),
  Sourate(id: 88,  nameAr: 'الغاشية',       nameFr: 'Al-Ghashiya',   verses: 26,  words: 93),
  Sourate(id: 89,  nameAr: 'الفجر',         nameFr: 'Al-Fajr',       verses: 30,  words: 139),
  Sourate(id: 90,  nameAr: 'البلد',         nameFr: 'Al-Balad',      verses: 20,  words: 82),
  Sourate(id: 91,  nameAr: 'الشمس',         nameFr: 'Ash-Shams',     verses: 15,  words: 54),
  Sourate(id: 92,  nameAr: 'الليل',         nameFr: 'Al-Layl',       verses: 21,  words: 71),
  Sourate(id: 93,  nameAr: 'الضحى',         nameFr: 'Ad-Duha',       verses: 11,  words: 40),
  Sourate(id: 94,  nameAr: 'الشرح',         nameFr: 'Ash-Sharh',     verses: 8,   words: 27),
  Sourate(id: 95,  nameAr: 'التين',         nameFr: 'At-Tin',        verses: 8,   words: 34),
  Sourate(id: 96,  nameAr: 'العلق',         nameFr: "Al-Alaq",       verses: 19,  words: 72),
  Sourate(id: 97,  nameAr: 'القدر',         nameFr: 'Al-Qadr',       verses: 5,   words: 30),
  Sourate(id: 98,  nameAr: 'البينة',        nameFr: 'Al-Bayyina',    verses: 8,   words: 94),
  Sourate(id: 99,  nameAr: 'الزلزلة',       nameFr: 'Az-Zalzala',    verses: 8,   words: 36),
  Sourate(id: 100, nameAr: 'العاديات',      nameFr: 'Al-Adiyat',     verses: 11,  words: 41),
  Sourate(id: 101, nameAr: 'القارعة',       nameFr: "Al-Qari'a",     verses: 11,  words: 36),
  Sourate(id: 102, nameAr: 'التكاثر',       nameFr: 'At-Takathur',   verses: 8,   words: 28),
  Sourate(id: 103, nameAr: 'العصر',         nameFr: "Al-Asr",        verses: 3,   words: 14),
  Sourate(id: 104, nameAr: 'الهمزة',        nameFr: 'Al-Humaza',     verses: 9,   words: 33),
  Sourate(id: 105, nameAr: 'الفيل',         nameFr: 'Al-Fil',        verses: 5,   words: 23),
  Sourate(id: 106, nameAr: 'قريش',          nameFr: 'Quraysh',       verses: 4,   words: 17),
  Sourate(id: 107, nameAr: 'الماعون',       nameFr: "Al-Ma'un",      verses: 7,   words: 25),
  Sourate(id: 108, nameAr: 'الكوثر',        nameFr: 'Al-Kawthar',    verses: 3,   words: 10),
  Sourate(id: 109, nameAr: 'الكافرون',      nameFr: 'Al-Kafirun',    verses: 6,   words: 26),
  Sourate(id: 110, nameAr: 'النصر',         nameFr: 'An-Nasr',       verses: 3,   words: 19),
  Sourate(id: 111, nameAr: 'المسد',         nameFr: 'Al-Masad',      verses: 5,   words: 23),
  Sourate(id: 112, nameAr: 'الإخلاص',       nameFr: 'Al-Ikhlas',     verses: 4,   words: 15),
  Sourate(id: 113, nameAr: 'الفلق',         nameFr: 'Al-Falaq',      verses: 5,   words: 23),
  Sourate(id: 114, nameAr: 'الناس',         nameFr: 'An-Nas',        verses: 6,   words: 20),
];

/// Numéro de Hizb (1–60) pour chaque sourate, basé sur la position
/// cumulative des versets dans le Coran (6236 versets, Al-Fatiha incluse).
/// Calculé une fois à l'initialisation — donnée de domaine, pas de l'UI.
final Map<int, int> sourateHizbMap = _buildHizbMap();

Map<int, int> _buildHizbMap() {
  int cumulative = 7; // Al-Fatiha (7 versets, exclue de allSourates)
  final map = <int, int>{};
  for (final s in allSourates) {
    map[s.id] = (cumulative / 6236 * 60).floor().clamp(0, 59) + 1;
    cumulative += s.verses;
  }
  return map;
}
